{% set name = "domcmc" %}
{% set version = "2.0.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: "../../"

build:
  number: 1

requirements:
  host:
    - pip
    - python =3.7.0
  run:
    - numpy >=1.17.0
    - python >=3.7.0
    - pytz
    - scipy

test:
  imports:
    - domcmc

about:
  home: "https://gitlab.science.gc.ca/dja001/domcmc"
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: 
  summary: "dominik's tools for reading fst files"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - dja001
